[package]
name = "nosni-check"
version = "0.1.0"
authors = ["quininer <quininer@live.com>"]
edition = "2018"

[dependencies]
structopt = "0.2"
tokio = "0.1"
tokio-rustls = "0.10.0-alpha.3"
hyper = "0.12"
webpki-roots = "0.16"
