[package]
name = "nosni-check"
version = "0.1.0"
authors = ["quininer <quininer@live.com>"]
edition = "2018"

[dependencies]
structopt = "0.3"
futures-util = "0.3"
tokio = { version = "0.2", features = [ "full" ] }
tokio-rustls = "0.14"
hyper = "0.13"
webpki-roots = "0.20"
