[mitm]
bind = "127.0.0.1:1087"
alpn = "h2, http%2F1.1"
cert = "./ca-cert.pem"
key = "./ca.pem"

[fragment]
bind = "127.0.0.1:1077"
size = [50, 120]
delay = [100, 300]

[doh]
addr = "127.0.0.1:443"
name = "your-doh-server"
sni = false
dnssec = true

[mapping]
"your.domain" = { sni = "fake.domain", addr = "127.0.0.1" }
"your2.domain" = { addr = "your3.domain", alpn = [ "http/1.1" ] }
