[package]
name = "mitmca"
version = "0.1.0"
authors = ["quininer <quininer@live.com>"]
edition = "2018"

[dependencies]
failure = "0.1"
publicsuffix = { version = "1", default-features = false }
cache_2q = "0.10"
lazy_static = "1"
if_chain = "0.1"
rand = "0.6"
rustls = "0.15"
rcgen = { version = "0.4", features = [ "x509-parser" ] }

[dev-dependencies]
webpki = "0.19"
untrusted = "0.6"

[build-dependencies]
publicsuffix = { version = "1", default-features = false }
reqwest = "0.9"
