[package]
name = "mitmca"
version = "0.1.0"
authors = ["quininer <quininer@live.com>"]
edition = "2018"

[dependencies]
snafu = "*"
psl = "*"
cache_2q = "0.10"
rand = "0.7"
rustls = "0.16"
rcgen = { version = "0.7", features = [ "x509-parser" ] }

[dev-dependencies]
webpki = "0.21"
untrusted = "0.7"
