[package]
name = "mitmca"
version = "0.1.0"
authors = ["quininer <quininer@live.com>"]
edition = "2018"

[dependencies]
snafu = "0.6"
psl = "0.4"
cache_2q = "0.10"
rand = "0.7"
rustls = "0.18"
rcgen = { version = "0.8", features = [ "x509-parser" ] }
chrono = "0.4"

[dev-dependencies]
webpki = "0.21"
